# -*- coding: utf-8 -*-
"""Figures 2 and 3 from the main article

Automatically generated by Colab.

"""

#Explicit Electrothermal LLP VO2 Model Reproducing Preisach Like Hysteresis for
#Memristive and Neuromorphic Devices

#Scientific Reports
#B. A. S. F. Sena 1,2,+,* and L. A. L. de Almeida1,+

#1 Federal University of ABC (UFABC), Center for Engineering, Modeling and
#Applied Social Sciences, Santo Andre, SP, 09210-580, Brazil

#2 Federal Institute of Sao Paulo (IFSP), Department of Electrical,
#São Paulo, SP, 01109-010, Brazil ˜

#* sena.bruno@ifsp.edu.br
#+ these authors contributed equally to this work


#This script reproduces Figures 2 and 3 from the main article,
#and Figures 1 and 2 from the Supplementary Information.

#This script was originally executed in a Google Colab environment;
#running it there is recommended for faster and smoother execution.

import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from scipy.integrate import solve_ivp

# ───────── Helper: Save Figure with Verification ─────────
def save_figure_with_verification(filename, folder=None, dpi=300, bbox_inches='tight'):
    """
    Save current Matplotlib figure to 'folder/filename' and verify.

    Parameters
    ----------
    filename : str
        File name, e.g. 'vo2_comparison_main.png'
    folder : str or None
        Destination folder. If None, uses current working directory.
    dpi : int
        Resolution in dots per inch.
    bbox_inches : str
        Bounding box option for plt.savefig.
    """
    try:
        # Decide directory
        if folder is None:
            folder = os.getcwd()
        else:
            os.makedirs(folder, exist_ok=True)

        full_path = os.path.join(folder, filename)

        plt.savefig(full_path, dpi=dpi, bbox_inches=bbox_inches)

        if os.path.exists(full_path):
            file_size = os.path.getsize(full_path) / 1024.0  # KB
            print(f"  ✅ Saved: {filename}")
            print(f"     Path: {os.path.abspath(full_path)}")
            print(f"     Size: {file_size:.1f} KB")
            return True
        else:
            print(f"  ❌ Failed to save: {filename}")
            return False
    except Exception as e:
        print(f"  ❌ Error saving {filename}: {str(e)}")
        return False

# ───────── Material / Thermal Parameters ────────────────
params = dict(
    w=6.7,                  # Hysteresis width [K]
    Tc=320.75,              # Critical temperature [K]
    beta=0.25,              # Slope parameter [K^-1]
    gama=0.99,              # Proximity function parameter (gamma)
    C_th=1.0e-5,            # Thermal capacitance [J/K]
    G_th=2.0e-4,            # Thermal conductance [W/K]
    T_sub=273.15 + 45.0,    # Substrate temperature [K]
    R0=140.0 + 1000.0,      # Metallic phase resistance [Ω]
    E_a=0.22                # Activation energy [eV]
)

# Boltzmann constant [eV/K]
k_B = 8.617e-5
params['E_a_over_kB'] = params['E_a'] / k_B  # ≈ 2553 K

# ───────── LLP Proximity Function and Helpers ───────────
def ProFuncVO2(x, gama):
    """Proximity function P(x) for VO2 material."""
    return (1.0 - np.sin(gama * x)) * (1.0 + np.tanh(np.pi**2 - 2.0*np.pi*x)) / 2.0

# P(0) for the Tpr normalization
params['P0'] = ProFuncVO2(0.0, params['gama'])

def g_of_T(Tn, Tr, Tpr, delta, p):
    """
    LLP conductance fraction g(T) for a given LLP state.
    Used both for the 'true' update and clone-and-evaluate.
    """
    x    = (Tn - Tr) / Tpr
    Teff = Tn + Tpr * ProFuncVO2(x, p['gama'])
    return 0.5 + 0.5 * np.tanh(
        p['beta'] * (delta * p['w'] / 2.0 + p['Tc'] - Teff)
    )

def R_of_T(Tn, g_val, p):
    """Resistance as a function of temperature and conductance."""
    return 17.0 * g_val * np.exp(p['E_a_over_kB'] / Tn) + p['R0']

# ───────── Clone-and-Evaluate dT/dt ─────────────────────
def dTdt_clone(Tn, V2, delta_freeze, Tr_freeze, Tpr_freeze, p):
    """
    Temperature derivative with clone-and-evaluate LLP:
    g(T) is evaluated from a frozen LLP state.
    """
    g_clone = g_of_T(Tn, Tr_freeze, Tpr_freeze, delta_freeze, p)
    P = V2 / R_of_T(Tn, g_clone, p)
    return (P - p['G_th'] * (Tn - p['T_sub'])) / p['C_th']

def euler_step_clone(Tn, V2, h, delta_freeze, Tr_freeze, Tpr_freeze, p):
    """Explicit Euler method with clone-evaluated g(T)."""
    return Tn + h * dTdt_clone(Tn, V2, delta_freeze, Tr_freeze, Tpr_freeze, p)

def rk4_step_clone(Tn, Vn2, Vn1_2, h, delta_freeze, Tr_freeze, Tpr_freeze, p):
    """4th order Runge–Kutta with clone-evaluated g(T)."""
    V_mid2 = 0.5*(Vn2 + Vn1_2)
    k1 = dTdt_clone(Tn,             Vn2,    delta_freeze, Tr_freeze, Tpr_freeze, p)
    k2 = dTdt_clone(Tn + 0.5*h*k1,  V_mid2, delta_freeze, Tr_freeze, Tpr_freeze, p)
    k3 = dTdt_clone(Tn + 0.5*h*k2,  V_mid2, delta_freeze, Tr_freeze, Tpr_freeze, p)
    k4 = dTdt_clone(Tn + h*k3,      Vn1_2,  delta_freeze, Tr_freeze, Tpr_freeze, p)
    return Tn + (h/6.0)*(k1 + 2.0*k2 + 2.0*k3 + k4)

# ───────── Event-Driven Simulation with Clone-Eval ──────
def simulate_system(t, V, method='euler'):
    """
    Simulate the electrothermal LLP–VO2 system with
    event-driven LLP and clone-and-evaluate architecture.

    method: 'euler', 'rk4', 'bdf', or 'radau'
    """
    V2 = V**2

    # Allocate vectors
    T_state   = np.zeros_like(t, dtype=float)
    g         = np.zeros_like(t, dtype=float)
    R         = np.zeros_like(t, dtype=float)
    delta_vec = np.zeros_like(t, dtype=int)
    Tpr_vec   = np.zeros_like(t, dtype=float)

    # Initial condition: start at substrate temperature
    T_state[0] = params['T_sub']

    # ---- Initial LLP state ----
    delta = +1              # initial direction (heating)
    Tr    = T_state[0]      # initial reversal at T_sub
    g0    = 0.5             # initial fraction (can be refined)

    P0   = params['P0']
    beta = params['beta']

    # Consistent initial proximity scale, including P(0) normalization
    Tpr = (delta*params['w']/2.0 + params['Tc']
           - (1.0/beta)*np.arctanh(2.0*g0 - 1.0)
           - Tr) / P0

    # True g and R at n=0
    g[0] = g_of_T(T_state[0], Tr, Tpr, delta, params)
    R[0] = R_of_T(T_state[0], g[0], params)
    delta_vec[0] = delta
    Tpr_vec[0]   = Tpr

    # For reversal detection via sign of discrete derivative
    h = t[1] - t[0]
    deriv_prev = 0.0
    sign_prev  = 0  # sign of previous derivative

    # Time integration over macro-steps defined by t[]
    for n in range(1, len(t)):
        # ---- 1) Freeze LLP state at beginning of macro-step ----
        delta_freeze = delta
        Tr_freeze    = Tr
        Tpr_freeze   = Tpr

        t0 = t[n-1]
        t1 = t[n]

        if method == 'euler':
            # Single explicit Euler step with clone-eval
            T_state[n] = euler_step_clone(
                T_state[n-1], V2[n-1], h,
                delta_freeze, Tr_freeze, Tpr_freeze, params
            )

        elif method == 'rk4':
            # Single RK4 step with clone-eval
            T_state[n] = rk4_step_clone(
                T_state[n-1], V2[n-1], V2[n], h,
                delta_freeze, Tr_freeze, Tpr_freeze, params
            )

        elif method in ('bdf', 'radau'):
            # One macro-step [t0, t1] using SciPy stiff solvers,
            # freezing the LLP state during this interval.
            def rhs(t_loc, T_loc):
                # interpolate V^2 at the local solver time
                V2_loc = np.interp(t_loc, t, V2)
                dT = dTdt_clone(
                    T_loc[0], V2_loc,
                    delta_freeze, Tr_freeze, Tpr_freeze, params
                )
                # IMPORTANT: return 1D array, not scalar
                return np.array([dT])

            sol = solve_ivp(
                rhs,
                (t0, t1),
                y0=np.array([T_state[n-1]]),
                method='BDF' if method == 'bdf' else 'Radau',
                rtol=1e-6,
                atol=1e-9,
                vectorized=False
            )
            # Take the final value at t1 as the macro-step result
            T_state[n] = sol.y[0, -1]

        else:
            raise ValueError("Unknown method: choose 'euler', 'rk4', 'bdf', or 'radau'")

        # ---- 2) Event-driven LLP update at end of macro-step ----
        deriv = (T_state[n] - T_state[n-1]) / h
        if deriv > 0:
            sign_new = +1
        elif deriv < 0:
            sign_new = -1
        else:
            sign_new = 0

        # Detect genuine reversal: sign change between successive steps
        if (sign_new != 0) and (sign_prev != 0) and (sign_new != sign_prev):
            # Hard left anchoring at (T_{n-1}, g_{n-1})
            Tr = T_state[n-1]
            gr = g[n-1]
            delta = sign_new

            # Recompute Tpr using full formula with P(0)
            Tpr = (delta*params['w']/2.0 + params['Tc']
                   - (1.0/beta)*np.arctanh(2.0*gr - 1.0)
                   - Tr) / P0

        # Store updated direction and Tpr
        delta_vec[n] = delta
        Tpr_vec[n]   = Tpr

        # Compute true g and R at the new temperature using updated LLP state
        g[n] = g_of_T(T_state[n], Tr, Tpr, delta, params)
        R[n] = R_of_T(T_state[n], g[n], params)

        # Update derivative sign memory
        deriv_prev = deriv
        if sign_new != 0:
            sign_prev = sign_new

    return T_state, g, R, delta_vec, Tpr_vec

# ───────── Simulation + Analysis ────────────────────────
if __name__ == "__main__":

    print("="*70)
    print("VO2 THERMAL HYSTERESIS SIMULATION - WITH FILE VERIFICATION")
    print("="*70)

    current_dir = os.getcwd()
    print(f"\n📁 Working Directory: {current_dir}")
    print(f"📝 Python script: {os.path.abspath(__file__) if '__file__' in globals() else 'Interactive mode'}")

    # Directory for figures
    fig_dir = os.path.join(current_dir, "figuras_vo2")
    print(f"📸 Figures will be saved in: {fig_dir}")

    # Time and excitation
    t_rk4   = np.linspace(0, 8, 3000)    # RK4 macro-grid
    t_bdf   = t_rk4.copy()               # BDF on same macro-grid
    t_radau = t_rk4.copy()               # Radau on same macro-grid
    t_euler = np.linspace(0, 8, 15000)    # Euler macro-grid

    V_rk4   = 6.0*np.exp(-0.4*t_rk4)*np.sin(2.0*np.pi*t_rk4)
    V_bdf   = 6.0*np.exp(-0.4*t_bdf)*np.sin(2.0*np.pi*t_bdf)
    V_radau = 6.0*np.exp(-0.4*t_radau)*np.sin(2.0*np.pi*t_radau)
    V_euler = 6.0*np.exp(-0.4*t_euler)*np.sin(2.0*np.pi*t_euler)

    print("Running RK4 simulation...")
    T_rk4, g_rk4, R_rk4, delta_rk4, Tpr_rk4 = simulate_system(t_rk4, V_rk4, method='rk4')

    print("Running Euler simulation...")
    T_euler, g_euler, R_euler, delta_euler, Tpr_euler = simulate_system(t_euler, V_euler, method='euler')

    print("Running BDF simulation...")
    T_bdf, g_bdf, R_bdf, delta_bdf, Tpr_bdf = simulate_system(t_bdf, V_bdf, method='bdf')

    print("Running Radau simulation...")
    T_radau, g_radau, R_radau, delta_radau, Tpr_radau = simulate_system(t_radau, V_radau, method='radau')

    # ───────── Interpolation for Direct Comparison ──────
    T_rk4_interp_e = np.interp(t_euler, t_rk4, T_rk4)
    g_rk4_interp_e = np.interp(t_euler, t_rk4, g_rk4)

    # Errors Euler vs RK4 (on Euler time grid)
    error_T_e = T_euler - T_rk4_interp_e
    error_g_e = g_euler - g_rk4_interp_e

    MAE_T_e       = np.mean(np.abs(error_T_e))
    RMSE_T_e      = np.sqrt(np.mean(error_T_e**2))
    MAX_error_T_e = np.max(np.abs(error_T_e))

    MAE_g_e       = np.mean(np.abs(error_g_e))
    RMSE_g_e      = np.sqrt(np.mean(error_g_e**2))
    MAX_error_g_e = np.max(np.abs(error_g_e))

    # Errors BDF vs RK4 (same grid)
    error_T_b = T_bdf - T_rk4
    error_g_b = g_bdf - g_rk4

    MAE_T_b       = np.mean(np.abs(error_T_b))
    RMSE_T_b      = np.sqrt(np.mean(error_T_b**2))
    MAX_error_T_b = np.max(np.abs(error_T_b))

    MAE_g_b       = np.mean(np.abs(error_g_b))
    RMSE_g_b      = np.sqrt(np.mean(error_g_b**2))
    MAX_error_g_b = np.max(np.abs(error_g_b))

    # Errors Radau vs RK4 (same grid)
    error_T_r = T_radau - T_rk4
    error_g_r = g_radau - g_rk4

    MAE_T_r       = np.mean(np.abs(error_T_r))
    RMSE_T_r      = np.sqrt(np.mean(error_T_r**2))
    MAX_error_T_r = np.max(np.abs(error_T_r))

    MAE_g_r       = np.mean(np.abs(error_g_r))
    RMSE_g_r      = np.sqrt(np.mean(error_g_r**2))
    MAX_error_g_r = np.max(np.abs(error_g_r))

    # ───────── Comparative Plots: RK4 vs Euler ──────────
    plt.style.use('seaborn-v0_8-darkgrid')
    fig = plt.figure(figsize=(16, 10))
    gs = GridSpec(3, 3, figure=fig, hspace=0.3, wspace=0.3)

    # Custom colors
    color_rk4   = '#2E86AB'   # Blue
    color_euler = '#E63946'   # Red
    color_error = '#F77F00'   # Orange

    # Plot 1: Temperature vs Time
    ax1 = fig.add_subplot(gs[0, :2])
    ax1.plot(t_rk4, T_rk4, color=color_rk4, linewidth=2, label='RK4 (1000 pts)', alpha=0.8)
    ax1.plot(t_euler[::5], T_euler[::5], color=color_euler, linewidth=1,
             linestyle='--', label='Euler (5000 pts)', alpha=0.8)
    ax1.set_xlabel('Time (s)', fontsize=11)
    ax1.set_ylabel('Temperature (K)', fontsize=11)
    ax1.set_title('a) Temperature Comparison: RK4 vs Euler', fontsize=12, fontweight='bold')
    ax1.legend(fontsize=10, loc='upper right')
    ax1.grid(True, alpha=0.3)

    # Plot 2: Temperature Error (Euler - RK4)
    ax2 = fig.add_subplot(gs[0, 2])
    ax2.plot(t_euler, error_T_e, color=color_error, linewidth=1, alpha=0.7)
    ax2.axhline(y=0, color='black', linestyle='-', linewidth=0.5)
    ax2.set_xlabel('Time (s)', fontsize=11)
    ax2.set_ylabel('Error T (K)', fontsize=11)
    ax2.set_title('b) Error: T_Euler - T_RK4', fontsize=12, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    # f'MAE: {MAE_T_e:.2e} K'  # Formato: 1.23e-04
    ax2.text(0.5, 0.95,
             f'MAE: {MAE_T_e:.1e} K\nRMSE: {RMSE_T_e:.1e} K\nMax: {MAX_error_T_e:.1e} K',
             transform=ax2.transAxes, fontsize=9, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    # Plot 3: Hysteresis log(R) vs T
    ax3 = fig.add_subplot(gs[1, 0])
    ax3.semilogy(T_rk4, R_rk4, color=color_rk4, linewidth=2, label='RK4', alpha=0.8)
    ax3.semilogy(T_euler[::5], R_euler[::5], color=color_euler, linewidth=1,
                 linestyle='--', label='Euler', alpha=0.7)
    ax3.set_xlabel('Temperature (K)', fontsize=11)
    ax3.set_ylabel('Resistance R (Ω)', fontsize=11)
    ax3.set_title('c) Hysteresis: log(R) vs T', fontsize=12, fontweight='bold')
    ax3.legend(fontsize=10)
    ax3.grid(True, alpha=0.3)

    # Plot 4: Hysteresis g(T)
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.plot(T_rk4, g_rk4, color=color_rk4, linewidth=2, label='RK4', alpha=0.8)
    ax4.plot(T_euler[::5], g_euler[::5], color=color_euler, linewidth=1,
             linestyle='--', label='Euler', alpha=0.7)
    ax4.set_xlabel('Temperature (K)', fontsize=11)
    ax4.set_ylabel('Conductance Fraction g', fontsize=11)
    ax4.set_title('d) Hysteresis Curve: g(T)', fontsize=12, fontweight='bold')
    ax4.legend(fontsize=10)
    ax4.grid(True, alpha=0.3)

    # Plot 5: Conductance vs Time
    ax5 = fig.add_subplot(gs[1, 2])
    ax5.plot(t_rk4, g_rk4, color=color_rk4, linewidth=2, label='RK4', alpha=0.8)
    ax5.plot(t_euler[::5], g_euler[::5], color=color_euler, linewidth=1,
             linestyle='--', label='Euler', alpha=0.8)
    ax5.set_xlabel('Time (s)', fontsize=11)
    ax5.set_ylabel('Conductance Fraction g', fontsize=11)
    ax5.set_title('e) Conductance Evolution', fontsize=12, fontweight='bold')
    ax5.legend(fontsize=10)
    ax5.grid(True, alpha=0.3)

    # Plot 6: Conductance Error (Euler - RK4)
    ax6 = fig.add_subplot(gs[2, 0])
    ax6.plot(t_euler, error_g_e, color=color_error, linewidth=1, alpha=0.7)
    ax6.axhline(y=0, color='black', linestyle='-', linewidth=0.5)
    ax6.set_xlabel('Time (s)', fontsize=11)
    ax6.set_ylabel('Error g', fontsize=11)
    ax6.set_title('f) Error: g_Euler - g_RK4', fontsize=12, fontweight='bold')
    ax6.grid(True, alpha=0.3)
    ax6.text(0.5, 0.95,
             f'MAE: {MAE_g_e:.1e}\nRMSE: {RMSE_g_e:.1e}\nMax: {MAX_error_g_e:.1e}',
             transform=ax6.transAxes, fontsize=9, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    # Plot 7: Zoom in Critical Region
    ax7 = fig.add_subplot(gs[2, 1])
    idx_start, idx_end = 100, 300
    ax7.plot(t_rk4[idx_start:idx_end], T_rk4[idx_start:idx_end],
             color=color_rk4, linewidth=2.5, label='RK4',
             marker='o', markersize=3, alpha=0.8)
    ax7.plot(t_euler[idx_start*5:idx_end*5:5], T_euler[idx_start*5:idx_end*5:5],
             color=color_euler, linewidth=1.5, linestyle='--', label='Euler',
             marker='s', markersize=2, alpha=0.8)
    ax7.set_xlabel('Time (s)', fontsize=11)
    ax7.set_ylabel('Temperature (K)', fontsize=11)
    ax7.set_title('g) Zoom: Transition Region', fontsize=12, fontweight='bold')
    ax7.legend(fontsize=10)
    ax7.grid(True, alpha=0.3)

    # Plot 8: Error Histogram (Euler - RK4)
    ax8 = fig.add_subplot(gs[2, 2])
    ax8.hist(error_T_e, bins=50, color=color_error, alpha=0.7, edgecolor='black')
    ax8.axvline(x=0, color='red', linestyle='--', linewidth=1)
    ax8.axvline(x=np.mean(error_T_e), color='blue', linestyle='-', linewidth=1.5,
                label=f'Mean: {np.mean(error_T_e):.4f}')
    ax8.set_xlabel('Temperature Error (K)', fontsize=11)
    ax8.set_ylabel('Frequency', fontsize=11)
    ax8.set_title('h) Error Distribution (Euler - RK4)', fontsize=12, fontweight='bold')
    ax8.legend(fontsize=10)
    ax8.grid(True, alpha=0.3, axis='y')

    plt.tight_layout()

    print("Saving main comparison figure (RK4 vs Euler)...")
    save_figure_with_verification('vo2_comparison_main.png', folder=fig_dir)
    plt.show()

    # ───────── Detailed Statistical Analysis ─────────────
    print("\n" + "="*70)
    print("COMPARATIVE ANALYSIS: RK4 vs EULER (LLP Clone-and-Evaluate)")
    print("="*70)

    print("\n📊 TEMPERATURE STATISTICS (RK4):")
    print(f"    - Minimum: {T_rk4.min():.4f} K ({T_rk4.min()-273.15:.2f}°C)")
    print(f"    - Maximum: {T_rk4.max():.4f} K ({T_rk4.max()-273.15:.2f}°C)")
    print(f"    - Mean:    {T_rk4.mean():.4f} K ({T_rk4.mean()-273.15:.2f}°C)")
    print(f"    - Std Dev: {T_rk4.std():.4f} K")

    print("\n📊 TEMPERATURE STATISTICS (Euler):")
    print(f"    - Minimum: {T_euler.min():.4f} K ({T_euler.min()-273.15:.2f}°C)")
    print(f"    - Maximum: {T_euler.max():.4f} K ({T_euler.max()-273.15:.2f}°C)")
    print(f"    - Mean:    {T_euler.mean():.4f} K ({T_euler.mean()-273.15:.2f}°C)")
    print(f"    - Std Dev: {T_euler.std():.4f} K")

    print("\n📈 ERROR METRICS (Euler vs RK4):")
    print(f"  Temperature:")
    print(f"    - MAE:  {MAE_T_e:.6f} K")
    print(f"    - RMSE: {RMSE_T_e:.6f} K")
    print(f"    - Max:  {MAX_error_T_e:.6f} K")
    delta_T_mean = np.mean(np.abs(T_rk4 - params['T_sub']))
    if delta_T_mean > 0:
        print(f"    - Relative mean error (vs ΔT from T_sub): "
              f"{100.0*MAE_T_e/delta_T_mean:.2f}%")
    print(f"  Conductance:")
    print(f"    - MAE:  {MAE_g_e:.8f}")
    print(f"    - RMSE: {RMSE_g_e:.8f}")
    print(f"    - Max:  {MAX_error_g_e:.8f}")
    if np.mean(g_rk4) != 0:
        print(f"    - Relative mean error: {100.0*MAE_g_e/np.mean(g_rk4):.2f}%")

    print("\n⚙️ COMPUTATIONAL EFFICIENCY (macro-level):")
    print(f"  RK4:")
    print(f"    - Points: {len(t_rk4)}")
    print(f"    - Step size: {t_rk4[1]-t_rk4[0]:.6f} s")
    print(f"    - f evaluations per step: 4")
    print(f"    - Total f evaluations: {len(t_rk4)*4}")
    print(f"  Euler:")
    print(f"    - Points: {len(t_euler)}")
    print(f"    - Step size: {t_euler[1]-t_euler[0]:.6f} s")
    print(f"    - f evaluations per step: 1")
    print(f"    - Total f evaluations: {len(t_euler)*1}")
    print(f"  BDF:")
    print(f"    - Macro-steps: {len(t_bdf)}")
    print(f"    - Step size (macro): {t_bdf[1]-t_bdf[0]:.6f} s")
    print(f"    - Internal f evaluations: solver-dependent (solve_ivp-BDF)")
    print(f"  Radau:")
    print(f"    - Macro-steps: {len(t_radau)}")
    print(f"    - Step size (macro): {t_radau[1]-t_radau[0]:.6f} s")
    print(f"    - Internal f evaluations: solver-dependent (solve_ivp-Radau)")

    print("\n🔄 HYSTERESIS ANALYSIS:")
    print(f"  Number of detected reversals:")
    print(f"    - RK4:   {np.sum(np.diff(delta_rk4) != 0)}")
    print(f"    - Euler: {np.sum(np.diff(delta_euler) != 0)}")
    print(f"    - BDF:   {np.sum(np.diff(delta_bdf) != 0)}")
    print(f"    - Radau: {np.sum(np.diff(delta_radau) != 0)}")
    print(f"  Estimated hysteresis width in g:")
    print(f"    - RK4:   {g_rk4.max() - g_rk4.min():.6f}")
    print(f"    - Euler: {g_euler.max() - g_euler.min():.6f}")
    print(f"    - BDF:   {g_bdf.max() - g_bdf.min():.6f}")
    print(f"    - Radau: {g_radau.max() - g_radau.min():.6f}")

    # ───────── Additional Plot: Phase Analysis (RK4 vs Euler) ─────
    fig2, axes = plt.subplots(2, 2, figsize=(12, 10))

    dTdt_rk4   = np.diff(T_rk4) / (t_rk4[1] - t_rk4[0])
    dTdt_euler = np.diff(T_euler) / (t_euler[1] - t_euler[0])

    axes[0, 0].plot(T_rk4[:-1], dTdt_rk4, color=color_rk4, linewidth=1.5,
                    label='RK4', alpha=0.7)
    axes[0, 0].plot(T_euler[:-1:5], dTdt_euler[::5], color=color_euler,
                    linewidth=1.0, linestyle='--', label='Euler', alpha=0.7)
    axes[0, 0].set_xlabel('Temperature T (K)')
    axes[0, 0].set_ylabel('dT/dt (K/s)')
    axes[0, 0].set_title('a) Phase Space: dT/dt vs T')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)

    axes[0, 1].semilogy(t_rk4, R_rk4, color=color_rk4, linewidth=1.5,
                        label='RK4', alpha=0.8)
    axes[0, 1].semilogy(t_euler[::5], R_euler[::5], color=color_euler,
                        linewidth=1.0, linestyle='--', label='Euler', alpha=0.8)
    axes[0, 1].set_xlabel('Time (s)')
    axes[0, 1].set_ylabel('Resistance R (Ω)')
    axes[0, 1].set_title('b) Resistance Evolution (log scale)', fontsize=12, fontweight='bold')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)

    P_rk4   = V_rk4**2 / R_rk4
    P_euler = V_euler**2 / R_euler
    axes[1, 0].plot(t_rk4, P_rk4*1000.0, color=color_rk4, linewidth=1.5,
                    label='RK4', alpha=0.8)
    axes[1, 0].plot(t_euler[::5], P_euler[::5]*1000.0, color=color_euler,
                    linewidth=1.0, linestyle='--', label='Euler', alpha=0.8)
    axes[1, 0].set_xlabel('Time (s)')
    axes[1, 0].set_ylabel('Power (mW)')
    axes[1, 0].set_title('c) Dissipated Power', fontsize=12, fontweight='bold')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)

    cumulative_error = np.cumsum(np.abs(error_T_e)) * (t_euler[1] - t_euler[0])
    axes[1, 1].plot(t_euler, cumulative_error, color=color_error,
                    linewidth=2.0, alpha=0.8)
    axes[1, 1].set_xlabel('Time (s)')
    axes[1, 1].set_ylabel('Cumulative Error (K·s)')
    axes[1, 1].set_title('d) Cumulative |T_Euler - T_RK4|')
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].fill_between(t_euler, 0, cumulative_error,
                            alpha=0.3, color=color_error)

    plt.tight_layout()

    print("Saving phase analysis figure...")
    save_figure_with_verification('vo2_phase_analysis.png', folder=fig_dir)
    plt.show()

    # ───────── Extra Plot: BDF vs RK4 ────────────────────
    fig3, axb = plt.subplots(2, 2, figsize=(12, 8))
    color_bdf = '#4CAF50'  # green

    axb[0, 0].plot(t_rk4, T_rk4, color=color_rk4, label='RK4')
    axb[0, 0].plot(t_bdf, T_bdf, color=color_bdf, linestyle='--', label='BDF')
    axb[0, 0].set_xlabel('Time (s)')
    axb[0, 0].set_ylabel('Temperature (K)')
    axb[0, 0].set_title('a) Temperature: RK4 vs BDF', fontsize=12, fontweight='bold')
    axb[0, 0].legend()
    axb[0, 0].grid(True, alpha=0.3)

    axb[0, 1].plot(t_rk4, error_T_b, color=color_bdf)
    axb[0, 1].axhline(0, color='black', linewidth=0.5)
    axb[0, 1].set_xlabel('Time (s)')
    axb[0, 1].set_ylabel('Error T (K)')
    axb[0, 1].set_title(f'b) Error: T_BDF - T_RK4\nMAE={MAE_T_b:.1e}, Max={MAX_error_T_b:.1e}')
    axb[0, 1].grid(True, alpha=0.3)

    axb[1, 0].plot(T_rk4, g_rk4, color=color_rk4, label='RK4')
    axb[1, 0].plot(T_bdf, g_bdf, color=color_bdf, linestyle='--', label='BDF')
    axb[1, 0].set_xlabel('Temperature (K)')
    axb[1, 0].set_ylabel('g')
    axb[1, 0].set_title('c) Hysteresis g(T): RK4 vs BDF')
    axb[1, 0].legend()
    axb[1, 0].grid(True, alpha=0.3)

    axb[1, 1].plot(t_rk4, error_g_b, color=color_bdf)
    axb[1, 1].axhline(0, color='black', linewidth=0.5)
    axb[1, 1].set_xlabel('Time (s)')
    axb[1, 1].set_ylabel('Error g')
    axb[1, 1].set_title(f'd) Error: g_BDF - g_RK4\nMAE={MAE_g_b:.1e}, Max={MAX_error_g_b:.1e}')
    axb[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()

    print("Saving BDF comparison figure...")
    save_figure_with_verification('vo2_bdf_comparison.png', folder=fig_dir)
    plt.show()

    # ───────── Extra Plot: Radau vs RK4 ──────────────────
    fig4, axr = plt.subplots(2, 2, figsize=(12, 8))
    color_radau = '#9C27B0'  # purple

    axr[0, 0].plot(t_rk4, T_rk4, color=color_rk4, label='RK4')
    axr[0, 0].plot(t_radau, T_radau, color=color_radau, linestyle='--', label='Radau')
    axr[0, 0].set_xlabel('Time (s)')
    axr[0, 0].set_ylabel('Temperature (K)')
    axr[0, 0].set_title('a) Temperature: RK4 vs Radau')
    axr[0, 0].legend()
    axr[0, 0].grid(True, alpha=0.3)

    axr[0, 1].plot(t_rk4, error_T_r, color=color_radau)
    axr[0, 1].axhline(0, color='black', linewidth=0.5)
    axr[0, 1].set_xlabel('Time (s)')
    axr[0, 1].set_ylabel('Error T (K)')
    axr[0, 1].set_title(f'b) Error: T_Radau - T_RK4\nMAE={MAE_T_r:.1e}, Max={MAX_error_T_r:.1e}')
    axr[0, 1].grid(True, alpha=0.3)

    axr[1, 0].plot(T_rk4, g_rk4, color=color_rk4, label='RK4')
    axr[1, 0].plot(T_radau, g_radau, color=color_radau, linestyle='--', label='Radau')
    axr[1, 0].set_xlabel('Temperature (K)')
    axr[1, 0].set_ylabel('g')
    axr[1, 0].set_title('c) Hysteresis g(T): RK4 vs Radau', fontsize=12, fontweight='bold')
    axr[1, 0].legend()
    axr[1, 0].grid(True, alpha=0.3)

    axr[1, 1].plot(t_rk4, error_g_r, color=color_radau)
    axr[1, 1].axhline(0, color='black', linewidth=0.5)
    axr[1, 1].set_xlabel('Time (s)')
    axr[1, 1].set_ylabel('Error g')
    axr[1, 1].set_title(f'd) Error: g_Radau - g_RK4\nMAE={MAE_g_r:.1e}, Max={MAX_error_g_r:.1e}')
    axr[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()

    print("Saving Radau comparison figure...")
    save_figure_with_verification('vo2_radau_comparison.png', folder=fig_dir)
    plt.show()

    print("\n✅ CONCLUSION:")
    print(f"  Euler (fine grid), BDF and Radau all track RK4 with very small errors.")
    print(f"  For a fixed budget of f-evaluations, RK4 remains very efficient;")
    print(f"  BDF and Radau are attractive when the dynamics become stiff or when")
    print(f"  coupling this LLP–VO2 block into larger SPICE-like electrothermal circuits.")
    print("="*70)
    print(f"\n📁 Figures saved in: {fig_dir}")
    print(f"   - vo2_comparison_main.png")
    print(f"   - vo2_phase_analysis.png")
    print(f"   - vo2_bdf_comparison.png")
    print(f"   - vo2_radau_comparison.png")